package com.example.loteria

var Baraja: Array<Carta> = arrayOf(
        Carta("El Alacran", R.drawable.alacran, R.raw.alacran),
        Carta("El Apache", R.drawable.apache, R.raw.apache),
        Carta("La Araña", R.drawable.arana, R.raw.arana),
        Carta("El Arbol", R.drawable.arbol, R.raw.arbol),
        Carta("El Arpa", R.drawable.arpa, R.raw.arpa),
        Carta("La Bandera", R.drawable.bandera, R.raw.bandera),
        Carta("El Bandolon", R.drawable.bandolon, R.raw.vandolon),
        Carta("El Barril", R.drawable.barril, R.raw.barril),
        Carta("El Borracho", R.drawable.borracho, R.raw.borracho),
        Carta("La Bota", R.drawable.bota, R.raw.bota),
        Carta("La Botella", R.drawable.botella, R.raw.botella),
        Carta("La Calavera", R.drawable.calavera, R.raw.calavera),
        Carta("El Camaron", R.drawable.camaron, R.raw.camaron),
        Carta("La Campana", R.drawable.campana, R.raw.campana),
        Carta("El Cantarito", R.drawable.cantarito, R.raw.cantarito),
        Carta("El Catrin", R.drawable.catrin, R.raw.catrin),
        Carta("El Cazo", R.drawable.cazo, R.raw.cazo),
        Carta("La Chalupa", R.drawable.chalupa, R.raw.chalupa),
        Carta("El Corazón", R.drawable.corazon, R.raw.corazon),
        Carta("La Corona", R.drawable.corona, R.raw.corona),
        Carta("El Cotorro", R.drawable.cotorro, R.raw.cotorro),
        Carta("La Dama", R.drawable.dama, R.raw.dama),
        Carta("El Diablito", R.drawable.diablito, R.raw.diablito),
        Carta("La Escalera", R.drawable.escalera, R.raw.escalera),
        Carta("La Estrella", R.drawable.estrella, R.raw.estrella),
        Carta("El Gallo", R.drawable.gallo, R.raw.gallo),
        Carta("La Garza", R.drawable.garza, R.raw.garza),
        Carta("El Gorrito", R.drawable.gorrito, R.raw.gorrito),
        Carta("Las Jaras", R.drawable.jaras, R.raw.jaras),
        Carta("La Luna", R.drawable.luna, R.raw.luna),
        Carta("La Maceta",R.drawable.maceta, R.raw.maceta),
        Carta("La Mano", R.drawable.mano, R.raw.mano),
        Carta("El Melon", R.drawable.melon, R.raw.melon),
        Carta("La Muerte", R.drawable.muerte, R.raw.muerte),
        Carta("El Mundo", R.drawable.mundo, R.raw.mundo),
        Carta("El Músico", R.drawable.musico, R.raw.musico),
        Carta("El Negrito", R.drawable.negrito, R.raw.negrito),
        Carta("El Nopal", R.drawable.nopal, R.raw.nopal),
        Carta("El Pajaro", R.drawable.pajaro, R.raw.pajaro),
        Carta("La Palma",R.drawable.palma, R.raw.palma),
        Carta("El Paraguas", R.drawable.paraguas, R.raw.paraguas),
        Carta("La Pera", R.drawable.pera, R.raw.pera),
        Carta("El Pescado", R.drawable.pescado, R.raw.pescado),
        Carta("El Pino", R.drawable.pino, R.raw.pino,),
        Carta("La Rana",R.drawable.rana, R.raw.rana),
        Carta("La Rosa", R.drawable.rosa, R.raw.rosa),
        Carta("La Sandia", R.drawable.sandia, R.raw.sandia),
        Carta("La Sirena", R.drawable.sirena, R.raw.sirena),
        Carta("El Sol", R.drawable.sol, R.raw.sol),
        Carta("El Soldado", R.drawable.soldado, R.raw.soldado),
        Carta("El Tambor", R.drawable.tambor, R.raw.tambor),
        Carta("El Valiente", R.drawable.valiente, R.raw.valiente),
        Carta("El Venado", R.drawable.venado, R.raw.venado),
        Carta("El Violoncello", R.drawable.violoncello, R.raw.violoncello)
    )